#!/usr/bin/env node
/**
 * Post-build script to ensure 404.html uses custom NotFoundContent
 * This fixes the issue where Next.js generates default 404.html instead of using app/not-found.tsx
 */

const fs = require('fs');
const path = require('path');

const REPO_NAME = process.env.BASE_PATH?.replace(/^\//, '') || process.env.REPO_NAME || 'portfolio';
const OUT_DIR = path.join(process.cwd(), 'out');

function readFile(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch (e) {
    return null;
  }
}

function writeFile(filePath, content) {
  fs.writeFileSync(filePath, content, 'utf8');
}

function hasCustomContent(content) {
  return content && (content.includes('NotFoundContent') || content.includes('Page not found'));
}

const root404Path = path.join(OUT_DIR, '404.html');
const notFoundPath = path.join(OUT_DIR, '_not-found', 'index.html');
const pages404Path = path.join(OUT_DIR, '404', 'index.html');

console.log('🔧 Fixing 404.html to use custom NotFoundContent...\n');

// Read files
const root404 = readFile(root404Path);
const notFound = readFile(notFoundPath);
const pages404 = readFile(pages404Path);

// Check if root 404 has custom content
if (root404 && hasCustomContent(root404)) {
  console.log('✓ 404.html already contains custom NotFoundContent');
  process.exit(0);
}

console.log('⚠ 404.html does not contain custom content');
console.log('Looking for custom content in alternative locations...\n');

// Priority 1: Check if _not-found/index.html has custom content (from app/not-found.tsx)
if (notFound && hasCustomContent(notFound)) {
  console.log('✓ Found custom content in out/_not-found/index.html (from app/not-found.tsx)');
  console.log('Copying to out/404.html...');
  writeFile(root404Path, notFound);
  console.log('✓ Successfully copied custom 404 content to out/404.html');
  process.exit(0);
}

// Priority 2: Check if pages/404.tsx output exists and has custom content
if (pages404 && hasCustomContent(pages404)) {
  console.log('✓ Found custom content in out/404/index.html (from pages/404.tsx)');
  console.log('Copying to out/404.html...');
  writeFile(root404Path, pages404);
  console.log('✓ Successfully copied custom 404 content to out/404.html');
  process.exit(0);
}

// If we get here, no custom content was found anywhere
console.error('❌ ERROR: No custom NotFoundContent found in any location');
console.error('Expected locations:');
console.error('  - out/_not-found/index.html (from app/not-found.tsx)');
console.error('  - out/404/index.html (from pages/404.tsx)');
console.error('  - out/404.html (should be generated by Next.js)');
console.error('\nThis indicates that neither app/not-found.tsx nor pages/404.tsx is being processed correctly during build.');
process.exit(1);
